### ISSUE TITLE
Support for v30?

### ISSUE THREAD

**Issue by Sunaries** [hexabits/nifskope#19]
![](https://cdn.discordapp.com/attachments/65830705023680512/345321626730233857/32232.png)

Unfortunately doesn't work with the models I have.

**Comment by hexabits** [comment]
This is not a NifSkope issue, it's a nifxml issue.  Nobody has really worked on nif.xml in any capacity for 30.x NIFs, let alone 30.2, which we've never heard of or seen.

The only NifSkope issue is that regardless of nifxml decoding progress, NifSkope will never display the NIFs past 20.5/20.6 because they switched to NiMesh/NiDataStream for the geometry.

If you're the same person as on our Discord, who wouldn't even tell us what game this is,  we can't even attempt to decode it since we don't have the game or its files.

**Comment by Sunaries** [comment]
@jonwd7 Sorry, I'm new to this.

I have not joined your Discord server so I am not that person. I'd be more willing to elaborate on this issue in the Discord server and provide assistance where needed. What is the URL?

**Comment by neomonkeus** [comment]
The first part of adding support is actually the nif format description, which is then used by our read/write  libraries. The better place to write the ticket in here - https://github.com/niftools/nifxml/issues
Can you share the nif and game in question please.

**Comment by josephcrowell** [comment]
Discord - https://forum.niftools.org/40-niftools-discord-server/
