### ISSUE TITLE
Load error at user verion 11, 34

### ISSUE THREAD

**Issue by dkspwndj** [hexabits/nifskope#23]
1.1.3 version nifskope saved 11, 34 user version nif open than error and can't open.

**Comment by hexabits** [comment]
Changing User Version or User Version 2 has **never** been a supported method of "converting".  There is absolutely nothing special being done when you do this.  It takes the same data in the file and then reinterprets it with the new versions,  which means if the data in a block changes location or size,  it will no longer be the same and it **will** get corrupted in some way. 

The only time this works is when you're "converting" between versions where the layout or size of the block doesn't change between versions.   It's essentially pure chance whether or not the versions can be changed on a file.  So, just because doing what you did sometimes works on some files does not mean that it is something you are meant to do and that we support doing.  Also because it has sometimes worked on some files doesn't mean that it is a bug that it didn't work on your file.
