### ISSUE TITLE
Does not build on Linux

### ISSUE THREAD

**Issue by tmbutterworth** [hexabits/nifskope#4]
Trying to build on Linux but encountering lots of problems:

Fixed two path issues in your makeconfig.sh file: 
cat ./doxygen/Doxyfile.in | sed 's/@VERSION@/'${version}'/' > Doxyfile
cat "../install/linux-install/nifskope.spec.in" | sed 's/@VERSION@/'${version}'/' > "../install/linux-install/nifskope.spec"

Contents in /lib/qhull/ are missing. I added in some from a separate download of qhull.

Linux requires "#include algorithm" for min/max functions
I fixed this in some files and adjusted to std::min and std::max.

Now I am currently stuck on an issue I haven't figured out how to fix yet. Are you planning to support Linux with 2.0 Dev?

Can you please see if openMW project would produce a Linux version of this built into openCS and Blender Integration thanks.

**Comment by hexabits** [comment]
The .sh file is there from 1.1.x or earlier.   I have no current plans on updating the stuff in ../install... it's basically there because I haven't deleted it yet.

However the last time I tried compiling the 2.0 branch with Qt Creator on Ubuntu it worked just fine.  If you want to build on Linux, try Qt Creator.  I had to get a few mesa3d libs or something, you can find which ones by searching the niftools forum. 

I don't really understand your OpenMW question, as we have nothing to do with them.  It's also very possible that nif.xml and NifSkope 2.0 contain several regressions for Morrowind meshes, so it'd be a lot of work just figuring out what's broken.

**Comment by psi29a** [comment]
With our with QtCreator, on Ubuntu, it compiles but fails to link because fsengine isn't included.

**Comment by psi29a** [comment]
OK, fixed this. :)  fsengine is now building.

https://github.com/niftools/nifskope/pull/101
