### ISSUE TITLE
Starfield fails to load meshes with a Mesh Path containing a period

### ISSUE THREAD

**Issue by JMPZ11** [hexabits/nifskope#77]
It would appear the '.' character is not permitted in the Mesh Path field. I tried using a dot to represent lod, and Starfield wouldn't show the object, while NifSkope doesn't report any errors and renders everything fine.

Might not hurt to make sure there's no dots in there so others don't make my mistake?

That is, I named the mesh file something like "awesomeshipmod.1.mesh" and put "awesomemods\awesomeshipmod.1" in the mesh path. When I changed it to "_1" it resolved.

Thanks!

**Comment by fo76utils** [comment]
This is due to how sanitizing asset paths currently handles extensions: it tries to ensure that the full path has ".mesh" extension, but any existing incorrect extension is removed first. So, "textures/image.png" becomes "textures/image.dds" instead of "textures/image.png.dds", for example. And "awesomeshipmod.1" is replaced with "awesomeshipmod.mesh".

It would be easy however to change this behavior so that the ".mesh" is always just appended if the path does not already end with ".mesh".

**Comment by JMPZ11** [comment]
I have wondered if there will be (or are) any consequences for not
following the hash-based naming convention used in vanilla. It seems like
something you wouldn't do without a good reason, given what a royal pain it
is.

Anyhoo - I've stopped trying to use meaningful mesh names - not for
compatibility. Pure laziness. Thanks as always!

**Comment by JMPZ11** [comment]
There isn't anything that needs to be done, so I'll go ahead and close this
